description:
  motd-format: "%n %v\n%m"
  server-name: "&6&lUltra&r&fVanilla"
  version-color: WHITE
  motds:
    - "We are testing!"
    - "Testing testing..."
    - "Today we are testing [REDACTED]"
    - "test"
chat:
  format: "&7[%t&7] &7<&r&{name-color}%p&7> &r&{chat-color}%m"
max:
  homes: 2
defaults:
  default-title:
    id: default
    name: "Guest"